name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # O deploy roda toda vez que vocÃª der push na main

permissions:
  contents: write # PermissÃ£o para o robÃ´ escrever na branch gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do cÃ³digo ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Instalar Node.js ğŸ”§
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar DependÃªncias e Build ğŸ—ï¸
        run: |
          npm ci
          npm run build

      - name: Deploy para a branch gh-pages ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # A pasta que o Vite gera
          branch: gh-pages # A branch que o GitHub Pages estÃ¡ lendo